module.exports = {
  ERC20Token: require('./build/contracts/ERC20.json'),
  Exchange: require('./build/contracts/Exchange.json'),
  ZRX: require('./build/contracts/ZRX.json'),
  MKR: require('./build/contracts/MKR.json'),
  BAT: require('./build/contracts/BAT.json'),
  REP: require('./build/contracts/REP.json'),
  BTM: require('./build/contracts/BTM.json'),
  NPXS: require('./build/contracts/NPXS.json'),
  OMG: require('./build/contracts/OMG.json'),
  WTC: require('./build/contracts/WTC.json'),
  KCS: require('./build/contracts/KCS.json'),
  GNT: require('./build/contracts/GNT.json'),
  TRX: require('./build/contracts/TRX.json'),
  TOMO: require('./build/contracts/TOMO.json'),
  PPT: require('./build/contracts/PPT.json'),
  SNT: require('./build/contracts/SNT.json'),
  FUN: require('./build/contracts/FUN.json'),
  MITH: require('./build/contracts/MITH.json'),
  AE: require('./build/contracts/AE.json'),
  LRC: require('./build/contracts/LRC.json'),
  KNC: require('./build/contracts/KNC.json'),
  LOOM: require('./build/contracts/LOOM.json'),
  WETH: require('./build/contracts/WETH.json'),
  DAI: require('./build/contracts/DAI.json'),
  DGX: require('./build/contracts/DGX.json'),
  AION: require('./build/contracts/AION.json')
};
